viewer:
  theme: dracula

panel:
  scrolling:
    horizontal:
      step: 4

input:
  mouse:
    doubleClickTimeout: 300ms

kubernetes:
  clusters:
    ttl: 2m

resources:
  # Default behavior: hide resources with zero objects
  showNonEmptyOnly: true
  # How often to re-peek hidden resources for changes when showNonEmptyOnly is true
  peekInterval: 30s
  # Default ordering: alphabetic by resource plural
  order: alpha
  # Favorites are used when order=favorites
  favorites: [pods, services, deployments, replicasets, statefulsets, daemonsets, jobs, cronjobs, configmaps, secrets, ingresses, networkpolicies, persistentvolumeclaims]

objects:
  # Object list ordering: name | -name | creation | -creation
  order: name
  # Columns mode for server-side Tables:
  # - normal: show priority 0 columns (kubectl default)
  # - wide: show all server-provided columns (like `kubectl get -o wide`)
  columns: normal
